name: Bazel

on:
   pull_request: {}
   push: {}

jobs:
  build_and_test_ubuntu:
    name: Linux Ubuntu 20.04 Bazel build <GCC 9.3.0>
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Build
      run: |
        bazelisk build --config=gcc9 //...
